### PR TITLE
Add Datastore Gapic files.

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Comment by jmuk** [comment]
Note that the generated file is in the same structure as #877 but grpc-loading is not fully delayed because of google-gax's problem.

**Comment by jmuk** [comment]
Cc: @swcloud

**Comment by quartzmo** [comment]
Thanks @jmuk!

**Comment by blowmage** [comment]
🤘

**Comment by swcloud** [comment]
LGTM

**Pull request merged**
