### PR TITLE
product refresh

### PR DESCRIPTION
**Pull request by y33zhang**
product refresh

### CODE REVIEW

**Comment by blowmage** [comment]
Exciting!

**Comment by y33zhang** [comment]
I work at google, please grant me cla (my email yyzhang@google.com)

**Comment by y33zhang** [comment]
I'm the contributor and I'm logged in correctly

**Comment by blowmage** [comment]
Can you update the PR to fix the code style violations?

**Comment by y33zhang** [comment]
@blowmage sure, can you point me to the code style violations?  I didn't see any review comments. thanks

**Comment by blowmage** [comment]
It's in the output of the failed builds. Right now only AppVeyor has completed, but Travis-CI will fail when it completes as well. I see a couple trailing white spaces and one line over 80 characters long. 

Scroll to the bottom of this page:

https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-ruby/build/1.0.224/job/e5agj63in5no9juq

**Comment by y33zhang** [comment]
@blowmage thanks!  corrected.

**Comment by hxiong388** [comment]
@y33zhang I just sent you an email in your corp email with instruction to setup your Github account and obtain CLA.

**Comment by blowmage** [comment]
I'm going to change the CLA label for this and accept it so we can get the release out.

**Pull request merged**
