### PR TITLE
Add skip_lookup to Storage

### PR DESCRIPTION
**Pull request by blowmage**
This PR adds the `skip_lookup` argument to `Project#bucket` and `Bucket#file`, which will allow for users to make method calls on `Bucket` and `File` without first retrieving the full resource. 

```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new

bucket = storage.bucket "my-todo-app", skip_lookup: true
file = bucket.file "avatars/heidi/400x400.png", skip_lookup: true
file.download "/var/todo-app/avatars/heidi/400x400.png" # API call
```

This can also be used in conjunction with `user_project`:

```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new

bucket = storage.bucket "my-todo-app", skip_lookup: true, user_project: true
file = bucket.file "avatars/heidi/400x400.png", skip_lookup: true
file.download "/var/todo-app/avatars/heidi/400x400.png" # API call
```
[refs #1588]

### CODE REVIEW

**Comment by blowmage** [comment]
@remi and @frankyn, can you look this over as well?

**Comment by frankyn** [comment]
@blowmage thanks for doing this! I tried using the skip_lookup and hit a bug when I try downloading a file after skipping the lookup. 

Steps to reproduce:
```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new
bucket  = storage.bucket "bucket_name", user_project: true, skip_lookup: true 
file        = bucket.file "file_name", skip_lookup: true
file.download "local_file_name"
```

Error
```ruby
Google::Cloud::Storage::FileVerificationError:
       The downloaded file failed MD5 verification.
```

**Comment by frankyn** [comment]
I updated my reproduction steps with more detail on permissions used.

**Comment by remi** [comment]
@blowmage Interface LGTM!

I haven't tested to see why this may be breaking for @frankyn. Any thoughts @blowmage?

**Comment by blowmage** [comment]
I think the verifier code is assuming the MD5 hash is always present, and the value is missing for a lazy File object. I'm pretty sure we expect that the MD5 hash value can be missing like it is for encrypted files, so I'm not entirely sure why its raising. I was hoping to look deeper into this today, but it will have to wait until tomorrow. Sorry.

**Comment by blowmage** [comment]
I've added a fix for the verification on download, PTAL.

**Comment by frankyn** [comment]
Thanks @blowmage, when will the storage gem be updated with these changes?

**Comment by blowmage** [comment]
We will likely release Storage at the same time as Pub/Sub. I don't yet know if that will be this week or next.

**Comment by frankyn** [comment]
Ah okay, this is currently blocking Ruby requester pays samples. Is it possible to push it out this sooner sometime this week?

**Comment by blowmage** [comment]
Yeah, I'll plan on releasing Storage tomorrow morning, assuming I can get a green build between now and then. :)

**Comment by frankyn** [comment]
Ah sorry about that. I appreciate your support! Thank you.

**Comment by blowmage** [comment]
This is [released in 1.4.0](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-storage%2Fv1.4.0).

**Pull request merged**
