### PR TITLE
Logger#info++ should not raise exceptions

### PR DESCRIPTION
**Pull request by stephan-nordnes-eriksen**
In some border-cases the `Logger#debug/info/warn/error/fatal` will raise exceptions, causing unexpected program flow. Example:

```
#...
logger = logging.logger "my_app", resource, env: :development

logger.debug "test"
#Can potentially raise the different kinds of Google::Cloud::Error
```

In my opinion, this is not to be expected of the logger class. This PR simply wraps the critical part of `logger#add` in a `begin/rescue` statement to prevent this.

### CODE REVIEW

**Comment by stephan-nordnes-eriksen** [comment]
So.. I originally added a CLA to another email. I have updated now. Can this be re-run somehow?

**Comment by blowmage** [comment]
Thanks for the PR @stephan-nordnes-eriksen! 

/cc @quartzmo @dazuma Thoughts on the Logger change of behavior?

**Comment by quartzmo** [comment]
I think I agree with @dazuma's comment in #929 that now that the default logger (not yet released) is non-blocking and does not raise errors,

> Logger methods generally should not raise errors, but I also consider the blocking Logger a special case. Probably a major reason why you'd use the blocking logger is that you want to see errors.

**Comment by stephan-nordnes-eriksen** [comment]
Any time schedule on the non-blocking logger?

**Comment by blowmage** [comment]
We are targeting Friday, if we can fix some issues with the async writer in the acceptance tests.

**Comment by quartzmo** [comment]
Now that the non-blocking Logger addresses the need for a Logger that does not raise errors, I am closing this PR. Thank you @stephan-nordnes-eriksen!

**Comment by stephan-nordnes-eriksen** [comment]
@quartzmo How was this resolved in the end? By swallowing the exceptions, or some other way?

**Comment by dazuma** [comment]
By default, the logger now makes RPC calls in a background thread. Any exceptions are raised in that thread but aren't reported to the caller.

**Pull request closed without merging**
