### PR TITLE
Updates to speech using GAPIC LRO wrapper.

### PR DESCRIPTION
**Pull request by landrito**

### CODE REVIEW

**Comment by blowmage** [comment]
I'll try to get this PR updated and passing tomorrow.

**Comment by landrito** [comment]
Thanks @blowmage!

**Comment by blowmage** [comment]
I get the following error when trying to use this code:

`LoadError: cannot load such file -- google/gax/operation`

That file path doesn't seem to exist. What version of `google-gax` will include it?

**Comment by landrito** [comment]
Ah yes, it seems `google-gax` needs to be updated. I'll get it updated ASAP.

**Comment by landrito** [comment]
Version `0.7.0` will include that file. We are holding off on publishing `0.7.0` because we are anticipating some changes to `google-gax` based on the feedback from this PR and expert review. Would you be able to make updates to this PR using the current master branch of `googleapis/gax-ruby`?

**Comment by blowmage** [comment]
We are releasing tomorrow, so we won't be putting this in master until after the release.

**Comment by landrito** [comment]
Going to hold off on this update until after some review in `googleapis/api-client-staging`

**Pull request closed without merging**
