### PR TITLE
Refresh logging protos

### LINKED ISSUE #1438: Force google-cloud-logging client lib to use V2 format when calling Logging API
After the issue in https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1239 had been fixed, we were able to get partial success error details in `metadata`. However the format is weird:

```
error:
#<GRPC::BadStatus: 3:Illegal character ':' in log name>
error metadata =
{"google.rpc.debuginfo-bin"=>"\x12\xBE\x03[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n)\\010\\001\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\002\\022\\030\\010\\007\\022\\024User not authorized.\" } }"}
```

And the index info is missing. (The error details should include mappings between the index and the error). After some investigation with Logging API team it turned out that this is because when calling Logging API, by default the V1 format is used, so we get something like:

```
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\001\\022\\030\\010\\007\\022\\024User not authorized.\" } }"
      }
```

While if we indicate we want to use V2 format, we will get some well-formed json:

```
      {
        "@type": "type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors",
        "logEntryErrors": {
          "0": {
            "code": 3,
            "message": "Illegal character ':' in log name"
          },
          "1": {
            "code": 7,
            "message": "User not authorized."
          }
        }
      },
```

To force v2 format, the client should use either the query param: `$apiFormat=2` or the header: `X-GOOG-API-FORMAT-VERSION: 2`. Can we force this client to use V2 format?

### PR DESCRIPTION
**Pull request by geigerj**
Note: this does not yet refresh the GAPIC; that's coming soon. This
is just to unblock #1438.

Fixes #1438

### CODE REVIEW

**Comment by blowmage** [comment]
@geigerj Who do you want to be assigned to merge this PR once the build passes and approved?

**Comment by geigerj** [comment]
@blowmage Do you mind merging and creating a release once the build passes?

**Comment by blowmage** [comment]
K, you can indicate who you want to handle that by assigning the PR to them too.

**Comment by geigerj** [comment]
@blowmage Sure, will do going forward.

**Comment by blowmage** [comment]
@geigerj When will we get updated GAPIC for Logging? I suppose we want to wait for updated GAPIC to expose the added functionality?

**Comment by geigerj** [comment]
@blowmage Yes, wait for the GAPIC update to expose the functionality. The updates are taking longer than expected (still some remaining code generator changes needed) but should be coming soon.

**Pull request merged**
