### PR TITLE
Stackdriver product rename

### PR DESCRIPTION
**Pull request by tmatsuo**
Renaming some APIs to Stackdriver brand

### CODE REVIEW

**Comment by quartzmo** [comment]
Thank you @tmatsuo! Sorry we missed this usage.

I found two more: [.yardopts](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/.yardopts#L2) and [backoff_test.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/test/google/cloud/logging/backoff_test.rb#L17). Do you want to change them in this PR?

[refs #750]

**Comment by tmatsuo** [comment]
yeah I can do that

**Comment by tmatsuo** [comment]
I already squashed since the changes are trivial, PTAL

**Comment by quartzmo** [comment]
LGTM! Will merge when the build is green. Thanks again.

**Pull request merged**
