### PR TITLE
Language version docs

### PR DESCRIPTION
**Pull request by quartzmo**

### CODE REVIEW

**Comment by landrito** [comment]
Why are we removing the beta warning?

**Comment by quartzmo** [comment]
It's no longer on the cloud.google.com docs.

**Comment by landrito** [comment]
Ah gotcha, consistency is good. I just wanted to verify that the SLA is still at a beta level. If so LGTM.

**Comment by quartzmo** [comment]
I searched the official docs for any mention of "beta" and found only [this usage](https://cloud.google.com/natural-language/pricing):

> As of December 1, 2016,the Beta pricing discount of 50% for the Cloud Natural Language API is no longer in effect. This page reflects current prices.

But if you are sure that the SLA is still beta, then maybe I should remove that commit. Happy to do it.

**Comment by blowmage** [comment]
When do we consider the Natural Language ruby gem to be Beta? currently the README lists it [as Alpha](https://github.com/GoogleCloudPlatform/google-cloud-ruby#cloud-natural-language-api-alpha).

**Comment by landrito** [comment]
Woops sorry NL should be alpha right now.

**Comment by landrito** [comment]
I think the confusion is that the API is v1 whereas the client is alpha. I think removing the beta documentation is fine since that was in reference to the API. The gem we will change to beta at a later date. Keep it alpha in the README.

**Pull request merged**
