### PR TITLE
Add grpc documentation class for GAPIC-enabled APIs

### PR DESCRIPTION
**Pull request by swcloud**
This is for issue #986

### CODE REVIEW

**Comment by swcloud** [comment]
@blowmage Could you please take a look at why only some of build jobs did not start?

**Comment by blowmage** [comment]
I manually cancelled the jobs. Travis-CI had some _major_ congestion yesterday, and I was trying to get some important builds to finish so we could release. I cancelled the jobs in an attempt to reduce the number of jobs that were waiting to be built. Unfortunately, it didn't work and we still had to wait upwards of 18 hours to get the builds to finish.

I restarted the 4 jobs that were cancelled yesterday.

**Comment by swcloud** [comment]
@blowmage Do you think this can be merged soon so that we can on track to declare Beta?

**Comment by quartzmo** [comment]
@swcloud LGTM. Do you want to close #967, since this PR includes those two files?

**Comment by swcloud** [comment]
Cool. I closed #967

**Comment by quartzmo** [comment]
@blowmage Is the location of these files in `lib` OK with you? Can I merge this?

**Comment by blowmage** [comment]
I think these files can exist in a directory other than `lib`, but that can happen after this PR is accepted. 

I haven't accepted this PR because it was discussed at standup that beta could proceed without documenting the low level API. But I have a feeling this ship has sailed so we might as well accept it now.

**Pull request merged**
