### PR TITLE
Kokoro migration

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**
Initial kokoro build with language

### CODE REVIEW

**Comment by blowmage** [comment]
How do we know the integration works? Will Kokoro update PRs like CircleCI and Travis-CI do?

**Comment by blowmage** [comment]
I see the check added to the GitHub PR now. It links to source.cloud.google.com.

The build only appears to be performing a `bundle update`, and only for Ruby 2.5. Is this PR still a WIP? Should it have the `do not merge` label?

**Comment by TheRoyalTnetennba** [comment]
Yeah, still working on it. Good call on the label. I'm gonna try to have it just more or less mirror what circleCI's set up to do for now, with the option to have it diff and test individual updated gems later on.

**Comment by blowmage** [comment]
Nothing stands out. I’ll look at it.

**Comment by blowmage** [comment]
I think the failure is due to an encoding difference. Is the default Kokoro encoding UTF-8?

I have pushed a change to the storage tests on this branch to see if it un-sticks the build. If it does, we can push that change in a separate PR so it won't clutter this one.

**Comment by blowmage** [comment]
Wait, Kokoro tails the output for you?!? Sign me up!

**Comment by blowmage** [comment]
@TheRoyalTnetennba Do you want me to submit the test fix on a different PR so you can rebase and remove my commit from this PR?

**Comment by TheRoyalTnetennba** [comment]
Good catch. Yeah, I'll rebase and set the locales for the images.

**Comment by blowmage** [comment]
Will Windows and OS X builds be part of this PR?

**Comment by dazuma** [comment]
Windows and OS X will come later. (And indeed my understanding is they still require some amount of infrastructural work, across all our languages.) For now we're trying to get it working end-to-end for Linux.

**Pull request merged**
