### PR TITLE
Ruby GAPIC: Dlp v2beta1

### PR DESCRIPTION
**Pull request by ethanbao**

### CODE REVIEW

**Comment by blowmage** [comment]
Does this PR supersede #1554? Should #1554 be closed in favor of this PR?

**Comment by geigerj** [comment]
@blowmage Yes, #1554 is obsolete. Closing.

**Comment by geigerj** [comment]
@ethanbao We will need to remove smoke tests (`toolkit` needs to be updated to put them in a different location) and update some metadata files before this is ready. Do you want me to work with you to do this, or do you want me to add commits to your branch?

**Comment by ethanbao** [comment]
Jacob, it would be easier if you can add commits to my branch directly.

**Pull request closed without merging**
