### PR TITLE
BigQuery: Remove unused service.query_config method

### PR DESCRIPTION
**Pull request by tswast**

### CODE REVIEW

**Comment by blowmage** [comment]
Yeah, it looks like this should have been removed when `#query` had its implementation changed to use `#query_job`.

**Comment by blowmage** [comment]
@tswast From now on can we make sure that only the folks the PRs are assigned to perform the merge?

**Comment by tswast** [comment]
Will do. Sorry about that. I didn't even scroll up to see that.

**Comment by blowmage** [comment]
NP. :+1:

**Pull request merged**
