### PR TITLE
Add streaming support for speech

### PR DESCRIPTION
**Pull request by swcloud**

### CODE REVIEW

**Comment by blowmage** [comment]
What version of google-gax does this depend on?

**Comment by swcloud** [comment]
There is no related change in google-gax for streaming support.

**Comment by hxiong388** [comment]
I played around with existing speech streaming and the change form this PR (had to manually update service.rb to use the new GAPIC method). Since the new method is just a grpc stub, so I think it's functionally same as current speech streaming implementation.

**Comment by blowmage** [comment]
I am the author of the new commit.

**Comment by blowmage** [comment]
Did a bunch of edge case testing to see if I could get the method to misbehave, but it worked as expected. Errors returned by the API were sent to the enumerator and not handled/re-raised by google-gax.

**Comment by quartzmo** [comment]
@blowmage Thanks for giving this an extra measure of manual testing!

**Pull request merged**
