### PR TITLE
Add gapic generated code for monitoring API

### PR DESCRIPTION
**Pull request by swcloud**
This is the same as https://github.com/googleapis/api-client-staging/tree/master/generated/ruby/google-cloud-ruby/google-cloud-monitoring

### CODE REVIEW

**Comment by quartzmo** [comment]
@swcloud Thanks, I just glanced over this, and for what it is, it LGTM.

**Comment by quartzmo** [comment]
@swcloud I created the `monitoring` label. ;)

**Comment by swcloud** [comment]
@quartzmo Can you please take a look at why AppVeyor build failed on Environment: RUBY_VERSION=23-x64?

**Comment by blowmage** [comment]
The failure was a gzip error during the `bundle update`. Might have been a networking issue during the build. I restarted it.

**Comment by swcloud** [comment]
@blowmage Any update on the build?

**Comment by blowmage** [comment]
Build is green.

**Comment by swcloud** [comment]
Cool, Thanks!

**Pull request merged**
