### PR TITLE
Change API name suffix from Api to Client for logging

### PR DESCRIPTION
**Pull request by swcloud**

### CODE REVIEW

**Comment by quartzmo** [comment]
@swcloud Can you add me as a contributor to your fork so that I can update this PR?

**Comment by swcloud** [comment]
@quartzmo Done.

**Comment by quartzmo** [comment]
I confirm that this is my commit and I am okay with these commits being contributed to Google.

**Comment by quartzmo** [comment]
@blowmage I believe this PR is good to merge. Acceptance tests passing locally for me.

**Pull request merged**
