### PR TITLE
Add Circle CI configuration

### PR DESCRIPTION
**Pull request by quartzmo**
This PR adds a minimal Circle CI configuration to the project, in order to test if it works. No Ruby version is specified.

[refs #1059]

### CODE REVIEW

**Comment by quartzmo** [comment]
No need to merge this yet, as it already succeeds in its first goal of launching a Circle CI build on the PR's fork/branch.

**Comment by quartzmo** [comment]
Circle CI's execution of `bundle exec rake travis:build` was extremely quick, <= 5 min, the same as I get locally.

**Comment by quartzmo** [comment]
With attempt #15, PR (pre-merge) testing for Ruby versions `2.1`, `2.2`, and `2.3` is now working. Version `2.0` still fails.

**Comment by quartzmo** [comment]
@blowmage This latest update built all 4 Ruby versions successfully.

**Comment by blowmage** [comment]
Great progress! Acceptance tests are next? Then moving the doc build and release process from travis to circleci?

**Comment by quartzmo** [comment]
Yes, I'll keep working on exact that.

**Pull request merged**
