### PR TITLE
Update headers to use generated ruby version.

### PR DESCRIPTION
**Pull request by landrito**
cc @bjwatson

### CODE REVIEW

**Comment by bjwatson** [comment]
We do, but I don't want to burn your cycles re-releasing them all right away, unless you think you can get it done in less than an hour.

Otherwise, just focus on updating Vision this week, and releasing NL as soon as the blocking issue has been resolved. The rest can be updated next week.

**Comment by blowmage** [comment]
We will plan on releasing major version bumps for Vision and NL tomorrow, and minor bumps for all other GRPC-based gems to get this change. I will merge this as soon as the Vision V1.1 build completes.

**Comment by blowmage** [comment]
@bjwatson All GRPC-based gems were released with this change yesterday.

**Comment by bjwatson** [comment]
Thanks, Mike!

**Pull request merged**
