### PR TITLE
Add BigQuery Query Parameters

### LINKED ISSUE #1070: Support BigQuery Query Parameters
[Query Parameters](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.query.queryParameters) are no longer marked `[experimental]`, so we should support them!

### PR DESCRIPTION
**Pull request by blowmage**
Implement BigQuery Query Parameters.

Positional Query Parameters:

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

dataset = bigquery.dataset "my_dataset"
data = dataset.query "SELECT * FROM users WHERE id = ?", 
                     params: [1234567890]
```

Named Query Parameters:

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

dataset = bigquery.dataset "my_dataset"
data = dataset.query "SELECT * FROM users WHERE id = @id", 
                     params: { id: 1234567890 }
```

- [x] Implement Query Parameters
- [x] Unit Tests
- [x] Acceptance Tests
- [x] Method-level Documentation
- [x] LegacySQL Documentation
- [ ] Overview Documentation

[closes #1070]

### CODE REVIEW

**Comment by blowmage** [comment]
@danoscarmike @bjwatson This PR is still a WIP, but can you look it over and let us know if you see any issues with the approach taken?

**Comment by blowmage** [comment]
I would appreciate feedback specifically on the Struct parameters. I'm having a hard time finding any code that uses a Struct parameter, and I'm unsure how they are intended to be used.

**Comment by danoscarmike** [comment]
@swcloud do you have bandwidth to look over this PR?  Solves for blocking beta issue #1070.

**Comment by blowmage** [comment]
At this point I think the code is in pretty good shape. It is as correct as we can make it with the information we have. But the addition of standard vs. legacy SQL is a pretty big change and we will need to review the documentation to make sure users understand it.

**Comment by quartzmo** [comment]
@blowmage Thanks for pairing on this and going over every detail with me. I'm going to take a pass over the docs now (as discussed offline), after I add those changes I think we should be ready to merge!

**Comment by blowmage** [comment]
I think the changes in this PR look simple at first, but conceptually it is quite large. The differences between legacy SQL and standard SQL is going to be a thing users will have to understand in order to use BigQuery well.

That said, I'm really happy with the Ruby API for providing positional and named query parameters. And I'm super happy we can maintain backwards compatibility without making the Ruby API overly convoluted.

**Comment by quartzmo** [comment]
I have signed the CLA and I am the author of the commits.

**Pull request merged**
