### PR TITLE
Upgrade Google API Client dependency

### PR DESCRIPTION
**Pull request by blowmage**
Update the dependency to the most recent release.

### CODE REVIEW

**Comment by dazuma** [comment]
We had a brief internal discussion where I argued that it should be okay to loosen the version requirement (i.e. changing to `~> 0.23` instead of `~> 0.23.0`). Restating the argument here.

Breaking changes will be of one of three types:
1. Human-driven backward-incompatible changes to the shared code or the interfaces generated by the generator. Historically, we have released such changes in a "minor" version update of the gem.
2. Deletion of an API. The automation that updates the gem in response to changes to API specs, responds by releasing a "minor" version update of the gem.
3. Updating of an API in a non-backward-compatible form. The automation responds by releasing a "teeny" version update of the gem.

Currently we are treating "minor" version updates as breaking (hence version restrictions like `~> 0.23.0`). My argument is that these are no longer really breaking. Consider the above types of changes:
1. We do not expect any further changes of this type, based on the current status of the gem. From the [readme](https://github.com/google/google-api-ruby-client): "_the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features._" Accordingly, based on the git commit history, no non-automated changes of any significance have been made in the past year. Therefore, we can be confident that human-driven breaking changes will rarely if ever happen in the future. (In case something does happen, we still have major versions we can bump to reflect that.)
2. None of the gems in this (google-cloud-ruby) repository should be dependent on an API that could be deleted from google-api-client—i.e. that google officially drops support for. (If that ever were actually to happen, we'd have a larger issue to address.) Thus, this type of change should not be a concern either.
3. This type of change is theoretically possible. (Not for a generally-available API, but potentially for a prerelease API.) However, if it were to cause a problem, even our _current_ version restriction would not protect against it, since the automation releases these changes as "teeny" updates.

Therefore, the current policy of guarding against minor version bumps isn't giving us any real benefit. We don't expect (1) or (2) to happen, and it's already not guarding against (3), so we lose nothing by loosening the restriction.

**Comment by blowmage** [comment]
I'm open to the argument, but we haven't seen breaking changes from the google-api-client gem on the patch/tiny releases, e.g. 0.19.7 to 0.19.8. We have seen breaking changes going from 0.8.x to 0.9.x, and from 0.11.x to 0.12.x. These breaking changes were communicated at the time, and we had to remove workarounds in the google-cloud-* gems when upgrading the dependency. If the gem again broke backwards compatibility before going to 1.0 I expect this would be in a minor release and not a patch/tiny release, and the current dependency would protect the google-cloud-* gems from breaking.

That said, I agree that we could loosen the dependency, as long as the risk is understood and folks agree the convenience in upgrading is worth the potential for broken gems in the future. We need a blessing from someone like @JustinBeckwith.

**Comment by JustinBeckwith** [comment]
I totally defer to @dazuma on this one.

**Comment by quartzmo** [comment]
I agree with @blowmage:

>  we could loosen the dependency, as long as the risk is understood and folks agree the convenience in upgrading is worth the potential for broken gems in the future. 

I am OK with the risk, which I also perceive as minor per @dazuma's points 1 and 2, above. I believe it is worth the convenience.

**Comment by dazuma** [comment]
Note that the breaking changes from 0.8 -> 0.9 and 0.11 -> 0.12 were both of type (1), which we no longer expect since that gem is in maintenance mode. And anyway, we now own that gem, so we control its policy. We can for example insist that, like google-cloud-core, no further breaking changes should ever be made.

**Comment by blowmage** [comment]
Great. This PR has been updated to loosen the dependency.

**Comment by dazuma** [comment]
It looks like there's also this line: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-core/Gemfile#L8

**Comment by blowmage** [comment]
AFAICT `google-cloud-core/Gemfile` is already part of this PR.

**Comment by blowmage** [comment]
> Have you run acceptance tests locally where possible? (Most importantly, BigQuery and Storage)

Yes, they look to pass for me, but I have not run them on all ruby versions.

**Comment by dazuma** [comment]
re: google-cloud-core/Gemfile, I'm sorry, my bad, I was looking at the wrong branch. 🙃

**Pull request merged**
