### PR TITLE
Bigquery udf support

### PR DESCRIPTION
**Pull request by haman29**

### CODE REVIEW

**Comment by quartzmo** [comment]
@haman29 Thank you for opening this PR! The [gcloud-common Contributing guide](https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/contributing) explains why the CLA is required. It looks like your change also breaks some [simple style rules](https://travis-ci.org/GoogleCloudPlatform/gcloud-ruby/jobs/102021982). It would also be great if you could squash your two commits into just one. Please let us know if you need any help!

**Comment by blowmage** [comment]
My understanding is that this pull request intends to add the query job's experimental [`userDefinedFunctionResources` configuration](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.query.userDefinedFunctionResources). This configuration looks to be added after BigQuery was added to gcloud and this is the first we've heard of it. To add this fully we will need the following:

- [ ] optional parameter when creating a query job
- [ ] passing build (tests and rubocop)
- [ ] tests for the optional parameter
- [ ] documentation for the optional parameter
- [ ] code examples demonstrating how to use the optional parameter

@haman29 Thank you for the pull request and making us aware of this new feature! If you can sign the contributor agreement make the code changes needed to pass the build we will be happy to accept this contribution. If you cannot make all the changes outlined above we will be happy to add them after accepting your pull request.

**Comment by blowmage** [comment]
BigQuery's user defined functions are also documented [here](https://cloud.google.com/bigquery/user-defined-functions).

**Comment by haman29** [comment]
@quartzmo thank you! I was able to sign a CLA.
> It would also be great if you could squash your two commits into just one.
I will take care of the following.

**Comment by haman29** [comment]
@blowmage thank you following!

> - [x] optional parameter when creating a query job
> - [ ] passing build (tests and rubocop)
> - [ ] tests for the optional parameter

I want to do these tasks. please wait a minuites.

> - [ ] documentation for the optional parameter
> - [ ] code examples demonstrating how to use the optional parameter

These tasks I would leave it up to you.
Because I'm not good at writing English.
sorry...

**Comment by blowmage** [comment]
Excellent! I am grateful to have you contributing, @haman29!

**Comment by quartzmo** [comment]
@haman29 You're still working on this PR, right?

We can add the documentation. But maybe in the documentation for the method, you can add a code example that shows a user-defined function? No English needed, just Ruby. :)

**Comment by haman29** [comment]
I'm sorry for being late...
i don't know why test failed on travis-ci.
please help me!

add code sample!
refs. https://cloud.google.com/bigquery/user-defined-functions

```ruby
udf = <<EOS
// The UDF
function urlDecode(row, emit) {
  emit({title: decodeHelper(row.title),
        requests: row.num_requests});
}

// Helper function for error handling
function decodeHelper(s) {
  try {
    return decodeURI(s);
  } catch (ex) {
    return s;
  }
}

// UDF registration
bigquery.defineFunction(
  'urlDecode',  // Name used to call the function from SQL

  ['title', 'num_requests'],  // Input column names

  // JSON representation of the output schema
  [{name: 'title', type: 'string'},
   {name: 'requests', type: 'integer'}],

  urlDecode  // The function reference
);
EOS


query = <<EOS
SELECT requests, title
FROM
  urlDecode(
    SELECT
      title, sum(requests) AS num_requests
    FROM
      [fh-bigquery:wikipedia.pagecounts_201504]
    WHERE language = 'fr'
    GROUP EACH BY title
  )
WHERE title LIKE '%ç%'
ORDER BY requests DESC
LIMIT 100
EOS


gcloud = Gcloud.new('project name', 'key name')
bigquery = gcloud.bigquery
job = bigquery.query_job query, udfs: [udf]
job.wait_until_done!
if !job.failed?
  job.query_results.each do |row|
    puts row["table_count"]
  end
end
```

**Comment by blowmage** [comment]
Hi @haman29, the reason the test fails is that you have not created the optional named argument `pdfs` on the `Gcloud::Bigquery::Project#query_job` method. The test is calling calling `#query_job` and passing the argument, but that argument is not defined on the method.

You can run the tests locally by running: `$ bundle exec rake test`

**Comment by quartzmo** [comment]
@haman29 I am going to place this PR `on hold` until the `[Experimental]` label is removed from [`query.userDefinedFunctionResources`](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.query.userDefinedFunctionResources). When that happens, we will be happy to help you complete it. Thanks again for your help with this exciting new feature!

**Comment by blowmage** [comment]
This feature is still listed as experimental. I'm going to close this PR until this changes. When it does please reopen or create a new PR. Thanks!

**Comment by blowmage** [comment]
This looks to no longer be marked experimental.

**Comment by quartzmo** [comment]
Replaced by #1703.

**Pull request closed without merging**
