### PR TITLE
Clarify Spanner staleness documentation

### LINKED ISSUE #1782: [Spanner] Ambiguous documentation with using staleness reads
While using the staleness parameter with `Google::Cloud::Spanner::Client#snapshot`, I found the [documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.44.0/google/cloud/spanner/client?method=snapshot-instance) confusing on what a Numerical value could be for this staleness parameter. 

After reviewing the code, I found that the value provided to the staleness parameter is [converted](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/service.rb#L345) into a Protobuf Duration object using [`Google::Cloud::Spanner::Convert#number_to_duration`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/convert.rb#L212). 

Based on implementation I'm expecting that a Float value will be converted to seconds and nanoseconds. This should be documented with values or explain how values are interpreted, because cloud.google.com [documentation](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#readonly) defines this parameter to be of Protobuf Duration object which can't be used to define this parameter at this time.

### PR DESCRIPTION
**Pull request by blowmage**
Update staleness documentation to provide a use example.

[closes #1782]

### CODE REVIEW

**Comment by frankyn** [comment]
Thanks @blowmage!

**Comment by vkedia** [comment]
Why do we take arbitrary Numeric type? Can we instead take a specific type to avoid confusion of this sort?

**Comment by vkedia** [comment]
Actually I think you should take in [Time](https://ruby-doc.org/core-2.2.0/Time.html) type. This would be consistent with how the spanner's TIMESTAMP type is represented in the library.

**Comment by frankyn** [comment]
@vkedia I thought the type for staleness was a Duration Protobuf object and not a Timestamp?

**Comment by blowmage** [comment]
The argument will mostly be an Integer or a Float, and Numeric is the base class for both. However, I don’t think the type is the what was confusing, I think confusing part was what the value was representing. It wasn’t clear the value was the number of seconds. That’s how I am understanding this request.

**Comment by blowmage** [comment]
This argument is not a TIMESTAMP value.

**Comment by vkedia** [comment]
Yeah sorry I got confused between the staleness and timestamp fields. My bad!

**Comment by frankyn** [comment]
In this PR it would be nice to provide a clarification to the documentation.

@blowmage  I do agree with @vkedia in the sense that it should be allowed to accept a specific type which reflects the cloud documentation for this API.  In short also support the Duration protobuf.

**Comment by blowmage** [comment]
What clarification are you looking for? I don’t follow. 

We don’t expose protobuf types in the Ruby API.  The goal is to be able to change the backend implementations (REST, GRPC) without changing the Ruby API. Users can use the low level API if they would rather deal with the protobuf structures.

**Comment by frankyn** [comment]
Ignore my clarification comment and thanks for the clarity for now exposing the protobuf types.

**Comment by frankyn** [comment]
Is this ready to be merged?

**Pull request merged**
