### PR TITLE
Rename parent to project in logging API

### PR DESCRIPTION
**Pull request by swcloud**
Please refer to https://github.com/googleapis/googleapis/pull/208.

Seems to be low-risk to me. @blowmage @quartzmo Could you please evaluate the risk to the veneer layer to see if we can make the change into the new release?

### CODE REVIEW

**Comment by blowmage** [comment]
I agree this seems low risk.

We aren't getting CI builds on PRs, so I'll pull this locally and make sure we don't have any issues with it. Should be later tonight.

**Comment by quartzmo** [comment]
@blowmage Thanks!

**Comment by quartzmo** [comment]
@swcloud I'm adding the `blocking beta` label, please remove it if you decide this does not need to be in the beta release.

**Comment by quartzmo** [comment]
So no further changes needed? Should I merge?

**Pull request merged**
