### PR TITLE
Bigquery query job

### PR DESCRIPTION
**Pull request by quartzmo**
This PR introduces new implementations of `Project#query` and `Dataset#query` that create a job and wait for it to complete by calling `getQueryResults`, then read data from the temporary table created by the job. To support this, the PR updates `QueryJob#wait_until_done!` to use `getQueryResults`.

Breaking changes:

* Remove timeout and dryrun parameters from `Project#query`
* Change return type of `Project#query` from QueryData to Data
* Remove timeout and dryrun parameters from `Dataset#query`
* Change return type of `Dataset#query` from QueryData to Data   
* Remove timeout parameter from `QueryJob#query_results`
* Change return type of `QueryJob#query_results` from QueryData to Data 
* Remove timeout and dryrun parameters from `View#data`
* Change return type of `View#data` from QueryData to Data
* Remove `QueryData`    

[refs #1623]

### CODE REVIEW

**Comment by quartzmo** [comment]
@blowmage Regarding the idea we had about also updating `View#data` to read using `TableDataList`, I don't think it's possible:

> You cannot use the TableDataList JSON API method to retrieve data from a view. 

from [Using Views](https://cloud.google.com/bigquery/docs/views).

**Comment by quartzmo** [comment]
I'm going to see if the same approach of a Query Job writing to a temporary table works for view queries. It seems like it should.

**Comment by blowmage** [comment]
We added `View#data` to be API compatible with `Table#data`, but we could always deprecate/remove it.

**Comment by quartzmo** [comment]
I'm adding a commit to the PR updating `View#data`, but I won't mind removing it (and the method) if you think that's a better long-run choice after looking at the commit.

**Pull request merged**
