### PR TITLE
Use Rake::TestTask for running tests

### PR DESCRIPTION
**Pull request by blowmage**
Use Rake::TestTask to ensure tests run when the task is invoked.
This fixes a problem where a task can invoke multiple sub-tasks,
but the test files won't run until the parent task completes.

### CODE REVIEW

**Comment by blowmage** [comment]
@dazuma, I expect this change will also require some changes to the synth.py files. Unfortunately, this is needed to get the build back to passing. (This, or reverting #2420.)

**Comment by dazuma** [comment]
Ouch. Okay, I think I'll just remove Rakefile updating outright from all the synth scripts.

**Comment by blowmage** [comment]
Things will get better when we have more control over the generator, right? :)

**Comment by dazuma** [comment]
okay, synth scripts updated.

**Pull request merged**
