### PR TITLE
Upgrade Language for V1

### PR DESCRIPTION
**Pull request by blowmage**
Upgrade language gem to the upcoming V1 API.

- [x] Call new `analyze_syntax` API
- [x] New new PartOfSpeech values
- [x] Add Entity#mid
- [x] Add Entity::Mention with type attribute
- [x] Add new `encoding` optional argument when getting #sentiment
- [x] Add Sentence
- [x] Add Sentiment#sentences
- [x] Add Sentiment#score
- [x] Remove Sentiment#polarity

There may be some additional documentation changes to be made, but I tried to document all parameter changes and update code examples in the same commits as the change.

### CODE REVIEW

**Comment by blowmage** [comment]
@monattar Feedback on this?

**Comment by quartzmo** [comment]
@blowmage Can I add a commit to this PR making docs changes/additions?

**Comment by blowmage** [comment]
@quartzmo Yes please!

**Comment by quartzmo** [comment]
I confirm that I am the author of the commits.

**Comment by blowmage** [comment]
Thanks @quartzmo! I will update the label to reflect your consent.

**Comment by blowmage** [comment]
I am :+1: on the documentation changes.

**Comment by blowmage** [comment]
Everything passes for me locally. Merging now so we don't have to wait for CI.

**Pull request merged**
