### PR TITLE
Spanner unbounded thread pool

### PR DESCRIPTION
**Pull request by blowmage**
This PR replaces the fixed thread pool with an unbounded thread pool that will expand and contract the number of threads as needed.

### CODE REVIEW

**Comment by blowmage** [comment]
@vkedia What do you think about this change?

**Comment by vkedia** [comment]
Why do we need to make this change? Have we observed any issues with the fixed thread pool?
Also can we allow user to specify a threapool with some default?

**Comment by blowmage** [comment]
One reason I can see for this change is memory overhead for less heavily used client instances. Also, currently there is no way for users to specify the size (or type) of the thread pool. That's sort of why I'm asking. :) Is configuration wanted?

@remi, since we are actively working on something similar for Pub/Sub, and I know you are working on Spanner code examples, do you have any thoughts on configuration for Spanner's Session Pool's Thread Pool?

**Comment by vkedia** [comment]
What is the current size of the thread pool. I don't think we should change to unbounded since we do want to throttle session creations by default. So can we keep the default to be a bounded thread pool and have users specify there own thread pool if needed?

**Comment by blowmage** [comment]
> What is the current size of the thread pool.

The current fixed thread pool size is double the number of CPUs:

```ruby
@thread_pool = Concurrent::FixedThreadPool.new(
  [2, Concurrent.processor_count*2].max
)
```

**Comment by blowmage** [comment]
I'll create a separate PR for the thread pool size configuration.

**Comment by blowmage** [comment]
Closing as this is not the direction we are going.

**Pull request closed without merging**
