### PR TITLE
Cloud Spanner WIP

### PR DESCRIPTION
**Pull request by blowmage**
This PR represents the work made so far on the Cloud Spanner implementation. It does not include the Client API. New issues will be made to track the implementation of the Client API.

### CODE REVIEW

**Comment by quartzmo** [comment]
I get the following error while running top-level acceptance tests:

```sh
google-cloud-ruby quartzmo$ bundle exec rake acceptance
No domain name found for the DNS acceptance tests.
rake aborted!
LoadError: cannot load such file -- google/gax/operation
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb:29:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb:29:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1.rb:17:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1.rb:17:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:20:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/service.rb:20:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/project.rb:18:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner/project.rb:18:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner.rb:17:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/lib/google/cloud/spanner.rb:17:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/acceptance/spanner_helper.rb:19:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/acceptance/spanner_helper.rb:19:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/acceptance/spanner/database_test.rb:15:in `require'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-spanner/acceptance/spanner/database_test.rb:15:in `<top (required)>'
/Users/quartzmo/code/google/codez/gcloud-ruby/Rakefile:116:in `require_relative'
...
```

**Comment by blowmage** [comment]
Hold off on merging this until we get a new version of the google-gax gem. The version of google-gax that this PR is currently using is incompatible with the version that the other gems are using in master. We need to get all the gems on the same version before this can be merged into master.

**Comment by blowmage** [comment]
@quartzmo This is ready to be reviewed. This is the same code that is in the `spanner` branch, and has successful builds, including acceptance tests.

**Comment by blowmage** [comment]
K, moving this to master so we can get the Spanner code running acceptance tests. More Spanner PRs will be submitted to complete the implementation.

**Pull request merged**
