### PR TITLE
Regenerate v1 to pickup timeout config changes

### PR DESCRIPTION
**Pull request by jbolinger**
We are regenerating this due to some configuration changes.

I left the doc changes from the generated code in but I'm not sure if that makes sense since nothing else has changed.

### CODE REVIEW

**Comment by blowmage** [comment]
Is this meant to replace #1977?

**Comment by jbolinger** [comment]
Oh, good catch @blowmage - it looks like the config values had already been updated when @geigerj created that PR. 

I got pinged by the speech team today and thought that they had made a new change. My bad, I'll close this one.

**Comment by blowmage** [comment]
If you want we can merge this and release a point release of the current library with the updated config.

**Comment by jbolinger** [comment]
I'll ask, but I'm hoping this will motivate them to just push the other one through.

**Pull request closed without merging**
