### PR TITLE
Google Cloud Configuration

### PR DESCRIPTION
**Pull request by blowmage**
This PR moves `Configuration` from stackdriver-core to google-cloud-core, so it may be used by non-Stackdriver gems. In doing so, it makes some subtle changes to how the default project_id and credentials are discovered. The order of lookup goes as follows:

1) Argument passed to constructor
2) Gem-specific configuration
3) Shared configuration
4) Environment variables
5) Known file paths (Credentials only)
6) GCE metadata lookup

### CODE REVIEW

**Comment by blowmage** [comment]
@dazuma @quartzmo I've only updated the existing Stackdriver gems so far, but I would like to apply these default lookup changes to all gems. I'm looking for feedback on these changes. Does this look correct to you so far?

**Comment by dazuma** [comment]
I reworked Heng's original config class when implementing config for [opencensus](https://github.com/census-instrumentation/opencensus-ruby), and we might consider copying [that config class](https://github.com/census-instrumentation/opencensus-ruby/blob/master/lib/opencensus/common/config.rb) instead. (I haven't pulled it out into a separate gem yet, but probably should do so.) The differences are:

* The stackdriver-core config class allows any config name by implementing `method_missing`. This allows users to misspell configs. The opencensus config class requires you to provide a schema, and only valid fields can be get/set.
* Standard methods like `method` are annoying in the stackdriver-core config class because `method_missing` doesn't capture them. You have to use the `[]` syntax to use a field with a name that collides with method of Object. (This workaround is used for the `debugger` subconfig in the debugger gem, for example.) The opencensus config class explicitly defines singleton methods for every field, so doesn't suffer from this problem.
* The opencensus config class provides basic validity checking (e.g. types) of values. Significantly, this also means it prevents applications from doing violence to the schema by, for example, replacing a whole subconfig with a simple value (which would result in difficult-to-understand errors later on).

Caveats of going this route:

* The syntax for defining the schema (e.g. the names of subconfigs) is a bit different, but this is a fairly small change for each api.
* The requirement that only declared fields can be set, is a potential backward compatibility issue. Currently stackdriver-core configs allow you to set a field of any name, even those that don't exist. Furthermore, illegal values are also accepted silently, and the library just has to deal with them. If we switch to the opencensus config implementation, setting a field that doesn't exist, or setting an illegal value, will generate an exception.

**Comment by dazuma** [comment]
Another alternative, and maybe a better option, we can consider an existing library such as [configatron](https://github.com/markbates/configatron).

**Comment by blowmage** [comment]
> Standard methods like `method` are annoying in the stackdriver-core config class because `method_missing` doesn't capture them.

If we inherit from BasicObject instead of Object we can side-step these issues.

**Comment by blowmage** [comment]
> consider an existing library such as configatron.

I am wary of adding a external dependency for something so core and intended to always be forwards compatible. But I agree we should look at it.

**Comment by blowmage** [comment]
> Caveats of going this route:
> 
> * The syntax for defining the schema (e.g. the names of subconfigs) is a bit different, but this is a fairly small change for each api.

Right, and I think this could be a problem, since these core libraries are supposed to be forwards compatible. Meaning, a gem released a year ago needs to work with the same shared dependencies as a gem released today. We would have to maintain both mechanisms for defining the schema.

> * The requirement that only declared fields can be set, is a potential backward compatibility issue. Currently stackdriver-core configs allow you to set a field of any name, even those that don't exist. Furthermore, illegal values are also accepted silently, and the library just has to deal with them. If we switch to the opencensus config implementation, setting a field that doesn't exist, or setting an illegal value, will generate an exception.

This is another concern. Would it be acceptable to warn instead of raise?

**Comment by dazuma** [comment]
>> Standard methods like method are annoying in the stackdriver-core config class because method_missing doesn't capture them.

> If we inherit from BasicObject instead of Object we can side-step these issues.

Inheriting from BasicObject tends to be awkward, as the object ends up not fitting well into the rest of the Ruby ecosystem (e.g. lack of `#inspect` or `#to_s` causes exceptions when pretty printing). I prefer defined methods over `BasicObject/method_missing` when possible.

>> The syntax for defining the schema (e.g. the names of subconfigs) is a bit different, but this is a fairly small change for each api.

> Right, and I think this could be a problem, since these core libraries are supposed to be forwards compatible.

Compatibility requires that we leave a compatible API in `Stackdriver::Core::Configuration`, not that the new `Google::Cloud::Configuration` have the same API. We're definitely free to change how the _new_ google-cloud-wide class wants schemas to be defined, as long as we (1) leave a suitable adapter in stackdriver-core, and (2) keep the same end-user API for the existing stackdriver configs. Which leads us to:

>> The requirement that only declared fields can be set, is a potential backward compatibility issue.

> This is another concern. Would it be acceptable to warn instead of raise?

Yes, good idea, we can do that.

I can try throwing together an alternate PR with the above, so we can see what it concretely looks like in comparison with the class from stackdriver-core.

**Comment by dazuma** [comment]
I added a commit with my proposed changes.

First, here are the changes:

*   I renamed `google/cloud/configuration.rb` to `google/cloud/config.rb` (and the corresponding class to `Google::Cloud::Config`). This is because if a user has an older `stackdriver-core` gem and a newer `google-cloud-core` gem, then both gems would expose that file path, and there is no guarantee which of the two files would get loaded and shadow the other.
*   I updated the `Google::Cloud::Config` class as discussed earlier:
    *   Inherited from `BasicObject`. This in turn required additional changes which I note below.
    *   Added basic validation that includes warning on unknown fields, and warning when simple type checks fail. It also supports default values. Moving forward we can consider just setting those defaults based on environment variables, rather than the current practice of having helper methods that query the config and fall back to the environment.
    *   All the existing `delete` and `clear` calls, as well as some `instance_variable_get` hackery, were present to reset config hierarchies during tests. To clean all that up, I provided a `reset!` method instead.
*   In order to preserve forward compatibility, I did the following:
    *   The class retains the legacy usage in the initializer and the `add_options` method, although those are considered deprecated.
    *   Warnings are disabled if a config object is created using the above legacy methods. This prevents warning spam when running old versions of the stackdriver gems which do not properly declare all the fields in their schema.
*   Each gem now defines the schema (using calls to `add_field!` and `add_config!`) for its own configuration. Additionally, the toplevel config object defined in `google-cloud-core` defines the toplevel schema including the global `project_id` and `credentials` fields, along with a few other global fields that the stackdriver gems are currently sharing (like `service_name`.)
*   I updated tests to get them to pass. Generally this meant switching to the `reset!` method. In some cases I had to modify test data to conform to the correct schema. In a few cases I had to replace `.must_equal` expectation syntax with a corresponding `assert` because configs no longer subclass `Object` and thus no longer pick up minitest's expectation methods.

Second, here is how "forward compatibility" is being retained.

In the case of an older `stackdriver-core` gem and a newer `google-cloud-core` gem:

*   `google-cloud-core` does not have a `google/cloud/configuration.rb` file, so no file collision will happen.
*   Both `stackdriver-core` and `google-cloud-core` will attempt to define the `Google::Cloud.configure` method. Regardless of what order these happen, the `google-cloud-core` version will win. This is because, `google-cloud-core` defines the method directly on the metaclass, whereas `stackdriver-core` does it by `extend`ing a module, which appends the method at the _end_ of the method search path rather than inserting it at the beginning. Therefore, in this case, `google-cloud-core` replaces `stackdriver-core`'s config class. It is thus important that the class remains compatible with older versions of the stackdriver gems that use it.

In the case of a newer `stackdriver-core` gem and an older service gem, e.g. an older `google-cloud-logger`. Note: the newer `stackdriver-core` depends on and thus implies a newer `google-cloud-core`.

*   Neither `stackdriver-core` nor `google-cloud-core` includes a `google/cloud/configuration.rb` file. It is thus important that none of the older versions of the stackdriver gems attempt to require that file directly.
*   Older stackdriver service gems assume the legacy config API. They also do not specify their schema (i.e. which fields are allowed and what types are allowed). However, the new config class detects this case by detecting usage of the legacy API, and responds by disabling warnings. So an old gem will not emit any warnings on bad config usage. Once the gem is updated, the new version will have a schema defined using the new API, and warnings will be enabled, so incorrect usage from that point will result in warnings being displayed.

Finally, a note on the validations. I almost gave up on putting them in, due to the complexity of maintaining compatibility with the older stackdriver gems that don't define their own schemas. However, the validations caught a bunch of cases that were missing in the documentation, and even caught a bug in `google-cloud-trace/lib/google/cloud/trace/rails.rb`, so I'm now glad we have them.

**Comment by dazuma** [comment]
All right, _all_ the tests are finally passing. 😜

I made one more subtle change to the project ID and creds lookup. The environment variables are now being used as _defaults_ for the configuration classes, which simplifies the lookup logic and, I hope, makes it a bit more transparent. That is, the lookup order is:

1. Argument passed to constructor
2. Gem-specific configuration, each field defaulting to gem-specific environment variables
3. Shared configuration, each field defaulting to shared environment variables
4. Known file paths (Credentials only)
5. GCE metadata lookup

The main semantic change over the list in the initial comment, is that the priority order of shared configuration field and gem-specific environment variables has been reversed: all gem-specific information now takes precedence over all shared information.

I also made `project` and `keyfile` _aliases_ of the `project_id` and `credentials` config fields, rather than deprecated alternate fields that have to be checked separately. This also simplifies the logic a bit.

I believe this is now in reasonable shape for merging. Are you guys okay with what I've done with this? If so, I can work on the rest of the libraries.

@blowmage are you okay with me converting _all_ the libraries in a single PR? It'll be pretty big. Alternatively, since compatibility is being retained, we should be able to break it into separate PRs and even stagger releases without risking breakage.

**Comment by dazuma** [comment]
BTW, I now have a local commit that migrates the rest of our handwritten libraries (but not the gapic-only libraries, for which I'm not sure what we want to do). So in addition to bigquery and datastore which are already done in this PR, I also have dns, pubsub, resource-manager, spanner, speech, storage, translate, and vision. Would y'all like those in this same PR, or in a separate PR afterwards?

**Comment by blowmage** [comment]
> Would y'all like those in this same PR, or in a separate PR afterwards?

In this PR please!

**Comment by blowmage** [comment]
> I made one more subtle change to the project ID and creds lookup. The environment variables are now being used as _defaults_ for the configuration classes, which simplifies the lookup logic and, I hope, makes it a bit more transparent.

This is a very interesting refactor. I need some more time to mull it over, but I really like the change so far. @quartzmo, what do you think?

**Comment by quartzmo** [comment]
@blowmage If you are asking me what I think of the lookup order:

>  all gem-specific information now takes precedence over all shared information.

I think that sounds correct.

**Comment by blowmage** [comment]
Right now we are using `Google::Auth::Credentials.default` do so all the credential lookup. But this refactor does solve an issue I've had with the `_JSON` credentials lookup, namely that `DATASTORE_CREDENTIALS_JSON` was a lower priority than `GOOGLE_CLOUD_CREDENTIALS`. If we applied the change to `project_id` to `credentials` then we could fix this. But it would also mean potentially making the credentials ENV VAR lookup twice, once in the configuration, and then again in `Credentials.default`.

**Comment by dazuma** [comment]
Added the remaining manual gems.

@blowmage I didn't realize that `Google::Auth::Credentials.default` was doing its own lookup as well. I'll try to understand how that interacts.

**Comment by blowmage** [comment]
> I didn't realize that `Google::Auth::Credentials.default` was doing its own lookup as well. I'll try to understand how that interacts.

It was taken from google-cloud-ruby and not changed. If I had known it was being copied I would have said something before it was released. But, it makes sense for purely generated libraries (GAPIC), so I wouldn't try to remove it now. But I do think there is some value to configuring `credentials` the same way `project_id` is being configured as part of this PR. I think if it as doing extra credit. :)

**Comment by dazuma** [comment]
A couple other issues:

1. What exactly are the types allowed for `credentials`? Currently I'm allowing `String`, `Hash`, and `Google::Auth::Credentials`. Is `Google::Cloud::Credentials` still a thing? Are other types (e.g. `GRPC::Core::ChannelCredentials`) also possibilities? Should I just give up and allow `Object`?
2. @blowmage Did you want to convert the gapic-only libraries also? I wasn't clear on that. I think it can be done, but I'm not sure which files we can edit vs. which ones get regenerated. (e.g. is `google/cloud/bigtable.rb` handwritten or generated?)
3. I'm trying to determine whether any other configs should be promoted to shared configs. For example, `timeout` is widely used, but whether we should provide a shared default is not clear to me. Maybe we just hold off on these for now until it is clear, but any other opinions are welcome.

**Comment by blowmage** [comment]
> Is `Google::Cloud::Credentials` still a thing?

No, it remains in the `google-cloud-core` gem purely for backwards compatibility with older `google-cloud-*` gems. All current gems are using `Google::Auth::Credentials` now.

> Are other types (e.g. `GRPC::Core::ChannelCredentials`) also possibilities?

I'm fine leaving it strict for now. We can loosen the requirements later if we want.

> Did you want to convert the gapic-only libraries also?

No, those libraries don't have a dependency on google-cloud-core, so they won't be using the config API.

> I'm trying to determine whether any other configs should be promoted to shared configs.

I would leave it at `project_id` and `credentials` (and aliases) for now. Again, we can loosen this and add more in the future if warranted.

**Comment by blowmage** [comment]
> But this refactor does solve an issue I've had with the `_JSON` credentials lookup

So, it turns out we actually ran into this issue today with the ENV VAR ordering on Travis-CI, which is fun. 👍

**Comment by blowmage** [comment]
I'm going to rebase this branch on master to pick up the google-cloud-firestore code and add config to it.

**Comment by blowmage** [comment]
@dazuma What do you think of allowing the initial field value to be provided as a `Proc`? My concern is that if users change an environment variable, the change won't be recognized as it is today.

```ruby
require "google/cloud/logging" # loads config

ENV["LOGGING_PROJECT" = "my-project-id"

logging = Google::Cloud::Logging.new
logging.project #=> "my-project-id"
```

But with this change, the environment variable is determined when the config is loaded:

```ruby
require "google/cloud/logging" # loads config

ENV["LOGGING_PROJECT" = "my-project-id"

logging = Google::Cloud::Logging.new # <ArgumentError "project_id is missing">
```

Even calling `Config#reset!` will use the value when the configuration is first loaded.

```ruby
require "google/cloud/logging" # loads config

ENV["LOGGING_PROJECT" = "my-project-id"
Google::Cloud::Logging.configure.reset! # reload config

logging = Google::Cloud::Logging.new # <ArgumentError "project_id is missing">
```

But, if we can provide those default values as a Proc, then we can call it to get the default value:

```ruby
Google::Cloud.configure.add_config! :bigquery do |config|
  config.add_field! :project_id, lambda { ENV["BIGQUERY_PROJECT"] }, 
                    match: String
end
```

```ruby
require "google/cloud/logging" # loads config

ENV["LOGGING_PROJECT" = "my-project-id"
Google::Cloud::Logging.configure.reset! # call initial proc again

logging = Google::Cloud::Logging.new
logging.project #=> "my-project-id"
```

I ran into this with running the tests in my environment, where I have several environment variables set, and the stubs we add to the tests were too late, since the config was already loaded.

**Comment by dazuma** [comment]
@blowmage I was thinking about this as well. But I couldn't think of a real "user" use case for reloading defaults. Environment variables are generally meant for importing information into a process from the environment, not for the process to change its own information mid-flight. (That's why we have config in the first place.)

The issue with tests is real, but I got around that by having each service define an explicit `reload_configuration!` method to set up its config schema _and set the defaults_. [Here](https://github.com/blowmage/gcloud-ruby/blob/google-cloud-config/google-cloud-pubsub/lib/google/cloud/pubsub.rb#L563) is the example from pubsub. This gets called once on load to put together configuration initially, but you can call it again explicitly to reset all that info, including re-loading all the defaults. You can see that in, for example, the pubsub tests, one of which tests an environment variable. The [individual test](https://github.com/blowmage/gcloud-ruby/blob/google-cloud-config/google-cloud-pubsub/test/google/cloud/pubsub_test.rb#L223) sets the environment variable (via a stub) and then explicitly reloads configuration. Then an `after` block [reloads configuration again](https://github.com/blowmage/gcloud-ruby/blob/google-cloud-config/google-cloud-pubsub/test/google/cloud/pubsub_test.rb#L137) to restore the defaults with empty environment variables.

**Comment by blowmage** [comment]
> I got around that by having each service define an explicit reload_configuration! method

It seems we need to call both `Google::Cloud.reload_configuration!` and `Google::Cloud::Pubsub.reload_configuration!` then, and do this in many more tests, because I've got lots of unit test failures where my development environment variables are leaking into the tests.

I'm working on this, and adding Firestore support. Hope to have commits pushed to this PR in the next couple days.

**Comment by dazuma** [comment]
Hmm. You shouldn't need to call either of those methods unless you've changed the corresponding `ENV` variables for the test, and you want to restore the defaults. Perhaps the problem is that the tests currently assume that the `ENV` is basically empty when the tests are started—so, as you observed, if your development environment variables are leaking into the tests, they'll cause the configs not to have the expected values and a bunch of tests will fail. If that's the case, shouldn't the cleanest solution be just to clear out the relevant `ENV` variables at the beginning of the tests (maybe in the rakefiles)?

**Comment by blowmage** [comment]
I have added commits to support Firestore, and have updated the branch to adhere the updated style guide that was recently added to master. I believe this is ready to be reviewed.

**Pull request merged**
