### PR TITLE
Spanner Nested Merge

### PR DESCRIPTION
**Pull request by blowmage**
The merge logic needed to be updated to support deeply nested lists. @vkedia, can you verify this behavior is correct?

### CODE REVIEW

**Comment by blowmage** [comment]
The new test shows how deeply nested lists should be merged. The current [merge test](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/test/google/cloud/spanner/results/merge_test.rb) already tests merging lists with mixed value types, e.g. `numberValue`, `stringValue`, nullValue`, etc...

**Comment by vkedia** [comment]
Looks perfect. Thanks for the comprehensive test. BTW I could not find read_test.json file in this repo which has a test case that could have caught this:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/test/resources/com/google/cloud/spanner/read_tests.json#L150

**Comment by blowmage** [comment]
When we first wrote these tests that JSON wouldn't load in the Protobuf objects, so we had to diverge our tests.

**Comment by vkedia** [comment]
I see. What error were you getting?

**Comment by vkedia** [comment]
Also the chunks field in that JSON would load into protocol buffers of PartialResultSet. Everything else is not a protocol buffer.

**Comment by blowmage** [comment]
The PartialResultSet data defined in the JSON file wouldn't load in the protobuf objects. I don't remember what the problem was, but the data structure wasn't correct. So I recreated the test scenarios defined in the JSON file in test fixtures. This was in late 2016, IIRC.

**Pull request merged**
