### PR TITLE
Generate gapic client for language v1beta2

### PR DESCRIPTION
**Pull request by landrito**

### CODE REVIEW

**Comment by quartzmo** [comment]
@landrito Looks like you will need to exclude `v1beta2` from [Rubocop checks](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-language/.rubocop.yml#L7-L8).

**Comment by landrito** [comment]
Fixed!

**Comment by landrito** [comment]
Updates #1388

**Comment by blowmage** [comment]
The dependency on google-gax will need to be updated to 0.8.2 when this is released.

**Pull request merged**
