### PR TITLE
Added google-cloud-error_reporting gem

### PR DESCRIPTION
**Pull request by hxiong388**
Created the google-cloud-error_reporting gem, which contains the client API library and instrumentation library for Stackdriver Error Reporting API.

This is the first revision of the API (version 0.1.0), which only contains support for the reporting API. More APIs will be added in future revisions.

The client API library is structured similarly to other google-cloud-* libraries in this repo. All the documentation, unit tests, acceptance tests, other rake tasks should be compatible with the rest of the repo.

The instrumentation logic/code is defined in two files:
lib/google/cloud/error_reporting/middleware.rb
lib/google/cloud/error_reporting/rails.rb
The middleware.rb can be loaded along with rest of client API code, by invoking "require google/cloud/error_reporting". But the rails.rb has to be explicitly loaded by "require google/cloud/error_reporting/rails" in order to enable the Railtie integration logic.

### CODE REVIEW

**Comment by hxiong388** [comment]
Just had a meeting with Song Wang. We think it's the best if PR [891](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/891) gets merged first, then I will merge the Veneer and instrumentation code on top of the VTK code.

**Comment by blowmage** [comment]
@hxiong388 PR #891 was merged, and now this PR has conflicts. Can you please resolve the conflicts and update the PR? Once it has passed the builds we will merge. Thanks!

**Comment by hxiong388** [comment]
@blowmage, yup, I met with Song last week about this. This is our plan to puts his PR in first and I will do the merge. Thanks.

**Comment by hxiong388** [comment]
@blowmage, Converted the Veneer library I had to use GAPIC API. Now the two Veneer and VTK code exist side by side in google-cloud-error_reporting.

**Comment by hxiong388** [comment]
@blowmage Per discussions from last week and today, I have rewritten this PR to only contain error reporting instrumentation library that builds directly on top of GAPIC API. Should be able to merge now.

**Comment by blowmage** [comment]
Terrific. (Still waiting for a successful build.)

**Comment by blowmage** [comment]
@hxiong388 This PR now conflicts with master, and the build is failing. Can you update?

**Comment by hxiong388** [comment]
@blowmage Branch updated and stable. Ready for merge. Thanks.

**Comment by blowmage** [comment]
Great! Will merge on successful build. 

This is ready to be released, yes?

**Comment by hxiong388** [comment]
Yes, I believe this is ready.

**Pull request merged**
