### PR TITLE
update auth urls

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**
per https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/2254

### CODE REVIEW

**Comment by TheRoyalTnetennba** [comment]
Thanks @blowmage

**Comment by blowmage** [comment]
I just realized that the service account I was using specifies the URL to use, and so my test didn't use the URL changed in this PR. Would you like me to re-run my test, or are we confident enough that this change is okay?

**Comment by TheRoyalTnetennba** [comment]
I'd feel better retesting.

**Comment by blowmage** [comment]
I retested using a service account JSON file with those URLs removed. Everything passed again.

**Pull request merged**
