### PR TITLE
Memoize Logging Project#async_writer

### PR DESCRIPTION
**Pull request by blowmage**
All Loggers created by the Project object should use the same instance of AsyncWriter.
With `Project#async_writer` is memoized, there is no reason to have `AsyncWriter#logger`, so it is removed.

### CODE REVIEW

**Comment by blowmage** [comment]
@dazuma Here is a stab at [your comment](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/919#issuecomment-249687353) about memoizing `async_writer`. Please let us know if this is the right direction and if there are other changes you'd like to see.

**Comment by quartzmo** [comment]
As I wrote on #919:

> So, the memoization of the writer for `Project#logger` sounds great, as long as `Project#async_writer` always returns a new writer.

In other words, do the memoization in `Project#logger`, not in `Project#async_writer`?

**Comment by blowmage** [comment]
If @dazuma is okay with the memoization in this PR then I think it will be okay. Users can call `gcloud.speech` if they want a different `async_writer`, I suppose.

**Comment by dazuma** [comment]
I had intended to do the memoization in `Project#logger` instead. My reasons:

1. `Project#async_writer` takes an argument (and potentially other arguments in the future) for customizing the behavior of the AsyncWriter. This breaks memoization.
2. All the other such methods on Project are actual factories that create objects without memoizing. I think it would be confusing for `Project#async_writer` to behave differently. (In contrast, the AsyncWriter used by `Project#logger` is an internal implementation detail, so we're not causing confusion at the interface.)

If we want a Project method that returns the memoized AsyncWriter (which might be useful, but I don't think is required), I'd argue for creating a separate `Project#shared_async_writer` method.

**Comment by blowmage** [comment]
K, I'll wait for your PR then.

**Comment by dazuma** [comment]
Opened PR #928

**Comment by blowmage** [comment]
Superseded by #928

**Pull request closed without merging**
