### PR TITLE
Fixed outdated readme

### PR DESCRIPTION
**Pull request by TomasBarry**

### CODE REVIEW

**Comment by TomasBarry** [comment]
I signed it!

**Comment by quartzmo** [comment]
Hi @TomasBarry,

Thank you for opening this PR. Can you explain the rationale behind your change?

**Comment by blowmage** [comment]
FWIW, I believe the README is up-to-date with the latest version of google-cloud-bigquery.

**Comment by blowmage** [comment]
The README was updated in #1824 and is correct as of version 0.30.0. @TomasBarry, what version are you using?

**Comment by TomasBarry** [comment]
@quartzmo I am using `google-cloud-bigquery (0.25.0)`. 

Using:
```ruby
bigquery = Google::Cloud::Bigquery.new(
  project_id: "my-todo-project",
  credentials: "/path/to/keyfile.json"
)
```

Throws an error that `project_id` and `credentials` are unknown attributes. After quite a bit of digging through issues/StackOverflow I found a working solution was what I have changed the README to.

As @blowmage has said, if the version in the current README is valid for later versions then I am happy for this PR to be closed but it would be great if there was better documentation for version specific issues like this.

**Comment by blowmage** [comment]
The 0.25.0 documentation is found here:

https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.25.0/google/cloud/bigquery

That version is 6+ months old. I would suggest upgrading to get the latest features and performance tuning.

**Comment by TomasBarry** [comment]
@blowmage thanks for the link, couldn't seem to find those docs.

Happy to have this PR closed in that case.

**Pull request closed without merging**
