### PR TITLE
Add where parameter to view data

### PR DESCRIPTION
**Pull request by darthjee**
When getting data from the View object now you can add a where parameter to filter your results

### CODE REVIEW

**Comment by quartzmo** [comment]
Hi @darthjee, thank you for submitting this pull request!

It looks like you need to sign the CLA and that also the rubocop code style checks have failed. Try running `rake ci` locally. Also, test coverage for this addition will be needed. (See [CONTRIBUTING.md](CONTRIBUTING.md) for more information.)

**Comment by blowmage** [comment]
We added `View#data` so it would be the same as `Table#data`. But extending the method to be customizable seems to defeat the purpose to me. What do you think @quartzmo?

**Comment by quartzmo** [comment]
Personally I do not see a huge benefit from this change. But I am open to hearing the motivation behind it.

**Comment by darthjee** [comment]
Well, I signed the CLA

@quartzmo the thing is that I was trying to query the view, and the returned object was already requesting big_query before returning (unless it was the to_s method that made the request)

So I added the where clause to avoid such request

**Comment by blowmage** [comment]
Sorry for the misunderstanding. The correct way to query a view is using [`Project#query`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/bigquery/project?method=query-instance):

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

data = bigquery.query "SELECT name FROM [my_view]"

data.each do |row|
  puts row["name"]
end
```

**Comment by blowmage** [comment]
Adding Arel-inspired convenience methods (issue #203) is possibly related here.

**Comment by darthjee** [comment]
@blowmage 
Thank you,

I am closing the PR

**Pull request closed without merging**
