### PR TITLE
Add maximum_billing_tier option.

### PR DESCRIPTION
**Pull request by kmrshntr**
Make maximum_billing_tier option customizable.

### CODE REVIEW

**Comment by kmrshntr** [comment]
I signed it!

**Comment by quartzmo** [comment]
@kmrshntr Thank you for this pull request! Would you be interested in also adding another commit for the similar option `maximumBytesBilled` in this pull request? And also if it's not too much trouble, squashing your "Fix text" commit into the previous one?

**Comment by quartzmo** [comment]
The added option here is also lacking documentation. You can copy it from the [API docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs).

**Comment by quartzmo** [comment]
@kmrshntr Thank you for these commits. Do you have time to add documentation and unit tests for these three new options?

**Comment by quartzmo** [comment]
@blowmage Should we merge this PR, and follow up with our own PR for documentation and testing?

**Comment by blowmage** [comment]
@quartzmo Can you add an issue for the remaining changes?

**Comment by quartzmo** [comment]
@blowmage Yes, I will add the issue.

**Pull request merged**
