### PR TITLE
Regenerate Natural Language v1beta2 for ClassifyText method

### PR DESCRIPTION
**Pull request by geigerj**
Adds the `classify_text` method to the v1beta2 API.

### CODE REVIEW

**Comment by blowmage** [comment]
Is there an ETA for when this needs to be exposed in the Ruby API?

**Comment by geigerj** [comment]
@blowmage Do we expose the v1beta2 endpoint in the manual layer? If not, there's no work that needs to be done.

**Comment by blowmage** [comment]
Yes, we expose both [`V1`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-language/v0.27.0/google/cloud/language/v1/languageserviceclient) and [`V1beta2`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-language/v0.27.0/google/cloud/language/v1beta2/languageserviceclient). Right now the high level ruby API is using only `V1`. Just want to verify the plan is to continue using `V1` and not expose the `classify_test`/`categories` feature in the ruby API until it is added to `V1`, correct?

**Comment by geigerj** [comment]
Right, sorry, by "manual layer", I meant the high level API. And yes, we'll keep the features that have not yet been added to `V1` GAPIC-only.

**Comment by blowmage** [comment]
Do you want this released as google-cloud-language 0.27.1 today?

**Comment by geigerj** [comment]
Yes, a point release would be great.

**Comment by blowmage** [comment]
Natural Language 0.27.1 is released. ([release](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-language%2Fv0.27.1), [docs](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-language/v0.27.1/google/cloud/language/v1beta2/languageserviceclient))

**Pull request merged**
