### PR TITLE
Remove iam-related files from pubsub.

### LINKED ISSUE #942: Broken requires in gapic code for pubsub
Unfortunately we didn't catch this before merging #925: 

The require statement `require "google/iam/v1/iam_policy_services_pb"` in [`publisher_api.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_api.rb#L171) and [`subscriber_api.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_api.rb#L187) does not match the name of the file at [`lib/google/iam/v1/iam_policy_services.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/iam/v1/iam_policy_services.rb), which lacks the `_pb` suffix.

I have modified the require statements locally and can confirm that doing so resolves the immediate error, although I have not yet tested the IAM methods.

/cc @swcloud

### PR DESCRIPTION
**Pull request by jmuk**
Justification: IAM is an independent service but supplied to
pubsub as a mixin. This means that IAM can be used by something
else.

Because of this, we created an independent package,
grpc-google-iam-v1. Thus we don't have to have those grpc-related
files for IAM inside of pubsub -- but just add a dependency.

Fixes #942.

### CODE REVIEW

**Comment by quartzmo** [comment]
Thank you @jmuk!

**Comment by blowmage** [comment]
I'm curious why the IAM protobufs were turned into a separate gem, but the longrunning protobufs were added to `googleapis-common-protos`? Couldn't the IAM protobufs also be provided by `googleapis-common-protos`? What is the deciding factor between these two approaches?

**Comment by jmuk** [comment]
I am actually not 100% sure, but here is my understanding; longrunning is a common interface, while IAM is an independent service -- so it has API major version (v1), but some API like pubsub can embed it.
Cc @bjwatson for sanity check.

**Comment by bjwatson** [comment]
Yep, @jmuk is correct.

**Comment by quartzmo** [comment]
Tests failing at:

```sh
LoadError: cannot load such file -- google/iam/v1/iam_policy
/home/travis/build/GoogleCloudPlatform/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:19:in `require'
```

**Comment by jmuk** [comment]
Oops, sorry. The new commit is also necessary, since the path name has changed to the _pb suffix.

**Comment by quartzmo** [comment]
@jmuk Thanks for the update, going to check locally, hope to merge soon!

**Comment by quartzmo** [comment]
@jmuk I get 4 errors (all like the one shown below) when running acceptance tests:

```sh
$ git checkout jmuk/pubsub_iam
Note: checking out 'jmuk/pubsub_iam'.
...
HEAD is now at 258089b... Rename the path of iam_policy
$ cd google-cloud-pubsub/
$ bundle update
Fetching https://github.com/GoogleCloudPlatform/google-cloud-ruby.git
Fetching gem metadata from http://rubygems.org/.........
...
Installing grpc-google-iam-v1 0.6.8
Using google-cloud-pubsub 0.20.1 from source at `.`
Bundle updated!
$ bundle exec rake acceptance
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Run options: --seed 13897

# Running:

Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0003_allows permissions to be tested on a topic (1)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0003_allows permissions to be tested on a topic (2)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0003_allows permissions to be tested on a topic (3)
ERetrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0002_allows policy to be updated on a subscription (1)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0002_allows policy to be updated on a subscription (2)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0002_allows policy to be updated on a subscription (3)
ERetrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0004_allows permissions to be tested on a subscription (1)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0004_allows permissions to be tested on a subscription (2)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0004_allows permissions to be tested on a subscription (3)
ERetrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0001_allows policy to be updated on a topic (1)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0001_allows policy to be updated on a topic (2)
Retrying Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0001_allows policy to be updated on a topic (3)
E............

Finished in 28.674844s, 0.5580 runs/s, 13.4962 assertions/s.

  1) Error:
Google::Cloud::Pubsub::pubsub::IAM Policies and Permissions#test_0003_allows permissions to be tested on a topic:
LoadError: cannot load such file -- google/iam/v1/iam_policy_services
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:74:in `require'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:74:in `iam'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:291:in `block in test_topic_permissions'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:345:in `block in execute'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-core/lib/google/cloud/core/grpc_backoff.rb:77:in `block in execute'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-core/lib/google/cloud/core/grpc_backoff.rb:75:in `loop'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-core/lib/google/cloud/core/grpc_backoff.rb:75:in `execute'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:344:in `execute'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:291:in `test_topic_permissions'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb:436:in `test_permissions'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb:264:in `block (3 levels) in <top (required)>'



```

**Comment by quartzmo** [comment]
Adding the `_pb` suffix to the require at `lib/google/cloud/pubsub/service.rb:74` fixes the acceptance tests for me.

**Comment by quartzmo** [comment]
@jmuk I have a local branch in which I have converted google-cloud-pubsub to use the google-gax code. I tried to manually reproduce the changes in this PR there, and now get this error in acceptance tests:

```sh
Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 5:Resource not found (resource=gcloud-ruby-acceptance-2016-10-03t22-38-39z-9cb3f00b-434acba5).
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:352:in `rescue in block (2 levels) in retryable'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:346:in `block (2 levels) in retryable'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:345:in `loop'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:345:in `block in retryable'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:264:in `call'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:264:in `block in catch_errors'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:226:in `call'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:226:in `block in create_api_call'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:252:in `call'
    /Users/quartzmo/.rbenv/versions/2.2.3/gemsets/gcloud-ruby-yard/gems/google-gax-0.5.1/lib/google/gax/api_callable.rb:252:in `block in create_api_call'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_api.rb:345:in `call'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_api.rb:345:in `get_topic'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:99:in `block in get_topic'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:304:in `execute'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:99:in `get_topic'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/project.rb:144:in `topic'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb:21:in `retrieve_topic'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb:36:in `block (3 levels) in <top (required)>'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb:35:in `each'
    /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb:35:in `block (2 levels) in <top (required)>'
```

**Comment by jmuk** [comment]
GAX actually wraps grpc errors with its own error class as https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax/errors.rb, and the original errors are accessed through 'cause' of the errors.

If your code relies on the generated file, line 347 in service.rb (`rescue` for `execute`) would have to catch GaxError in addition to grpc errors.

**Comment by jmuk** [comment]
Please let me know if this design (GAX is wrapping errors with its own error class) doesn't look great, I'm open to change that.

**Comment by quartzmo** [comment]
@jmuk I think the wrapped errors approach is correct. But did you see my [earlier comment](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/952#issuecomment-251241903) about `cannot load such file -- google/iam/v1/iam_policy_services` while running acceptance tests using your branch?

**Comment by jmuk** [comment]
Ah, sorry, I saw it and fixed locally but not uploaded a patchset.

**Comment by quartzmo** [comment]
@jmuk Once acceptance tests pass for me locally, is this PR ready to merge?

**Comment by blowmage** [comment]
@jmuk write:

> Please let me know if this design (GAX is wrapping errors with its own error class) doesn't look great, I'm open to change that.

I didn't realize that _all_ errors were being wrapped into `Google::Gax::GaxError`. I figured it was a base error class for `Google::Gax::RetryError` to inherit from. This does break our error handling. We don't have access to `Error#cause` on Ruby 2.0, so we can't reliably get the `GRPC::BadStatus` error to figure out how to handle it.

If `Google::Gax::GaxError` would propagate the `#code`, `#details`, and `#metadata` from `GRPC::BadStatus` then we could just treat them as the same. Or, if `Google::Gax::GaxError` had a `#grpc_error` attribute that would give the original error we could use that.

**Comment by quartzmo** [comment]
This is how [our error creation relies on `code` or `status_code` to map gRPC errors to our own error types](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud/errors.rb#L22-L43).

**Comment by quartzmo** [comment]
@blowmage I think the 2.0 situation is [handled here](https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax/errors.rb#L44-L51).

**Comment by quartzmo** [comment]
@jmuk It will be less work for us to just continue to handle the gRPC errors, although I'm not sure that is the only concern to consider for your design.

**Comment by blowmage** [comment]
Oh, great. We can use `#cause` and make it work. Awesome!

**Comment by quartzmo** [comment]
Passes acceptance tests locally (note that these tests and the library do not yet use this GAX code.) Merging.

**Pull request merged**
