### PR TITLE
Removed unnecessary require "digest/sha2" in Cloud Storage Documentation & Test

### PR DESCRIPTION
**Pull request by frankyn**
Hi everyone,

After removing the [`encryption_key_sha256`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1109) parameter, I found an unnecessary `require "digest/sha2"` statement in the following locations in the _google-cloud-ruby_ documentation [1][2]. I also found it in an acceptance test where it should have been removed. I did test the acceptance test locally after the change was made.

This PR will clean that up. Thanks for reading. 

[1] https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/storage
[2] https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/storage/bucket

### CODE REVIEW

**Comment by frankyn** [comment]
I'm not sure what failed in CircleCI. I did notice this error is present in other PR's.

**Comment by quartzmo** [comment]
@frankyn I restarted the build now.

**Comment by quartzmo** [comment]
Failed again at `Action failed: rvm-exec 2.0.0-p648 gem install bundler`.

Sorry @frankyn, I really don't know what's up with this Circle Ci build.

**Comment by blowmage** [comment]
If the updated PR passes then let's merge with the "Rebase and merge" option so we don't commit the PR's merge commit to master.

**Comment by frankyn** [comment]
@quartzmo, almost completely passed (3/4)!  There seems to be an issue with a Speech test `Google::Cloud.speech#test_0001_:
RuntimeError: This code example is not yet mocked`

The PR @blowmage made did help.

**Comment by frankyn** [comment]
Wooo!! Everything passed this time, was it a fluke?

**Comment by quartzmo** [comment]
Yes, just a random order issue with Speech doctest.

**Comment by frankyn** [comment]
Thanks @quartzmo and @blowmage!

**Comment by quartzmo** [comment]
Thanks for this PR @frankyn. Sorry it was such a hassle to merge!

**Pull request merged**
