### PR TITLE
Update Spanner GAPIC config

### PR DESCRIPTION
**Pull request by geigerj**
Corresponds to upstream update here:
https://github.com/googleapis/googleapis/pull/424

### CODE REVIEW

**Comment by blowmage** [comment]
Should we plan on a point release tomorrow?

**Comment by geigerj** [comment]
@blowmage Yes, please.

**Comment by blowmage** [comment]
Will do.

**Comment by blowmage** [comment]
[Spanner 0.23.1 is released](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-spanner%2Fv0.23.1).

**Pull request merged**
