### PR TITLE
Use Rake::Task#invoke instead of sh

### PR DESCRIPTION
**Pull request by blowmage**
Use invoke to call rake tasks in the same Rakefile.
Only use sh when changing directories and running external rake tasks.

### CODE REVIEW

**Comment by blowmage** [comment]
@TheRoyalTnetennba do these two Kokoro failures make sense to you?

**Comment by TheRoyalTnetennba** [comment]
@blowmage it's been doing that sporadically. Looking into it.

**Comment by dazuma** [comment]
I might need to update a few of the synth scripts because they're updating Rakefiles. Lemme check...

**Comment by blowmage** [comment]
Yeah, I thought this may trigger some nightly PRs for the automated gems, so I didn't merge and include this in today's releases.

**Pull request merged**
