### PR TITLE
Add schema option to load method in table for bigquery

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
Please for more info, see issue #939 

There aren't tests yet, I need to be sure if this feature could be added. I tested with a real project and it works perfect.

### CODE REVIEW

**Comment by quartzmo** [comment]
👍  Cool!

**Comment by AlfonsoUceda** [comment]
@quartzmo @blowmage I've made the PR, can you check when you have time and share your opinions? thanks guys.

I used the schema approach instead the fields one because I think build a schema with its DSL is less verbose than using `Field` class.

**Comment by AlfonsoUceda** [comment]
@quartzmo @blowmage what do you think about this? thanks!

**Comment by blowmage** [comment]
@AlfonsoUceda I think we want something slightly different. I [commented](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/939#issuecomment-251741124) on your original issue. If you are interested we would love to accept another PR from you on this. If not, we can implement it. Just let us know.

**Comment by AlfonsoUceda** [comment]
@blowmage I've updated the PR.

About your [comment](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/939#issuecomment-251741124) with this `Project#create_table` you'd want to say `Dataset#create_table`, isn't it? I see you can use a block to config the schema, do you want to have this behaviour and passing the parameter?

About passing `fields` to `Table#load`, do we need to create a Schema from fields? I've seen we can pass fields to low level api in a easy way.

**Comment by AlfonsoUceda** [comment]
@blowmage @quartzmo did you have time to take a look?

**Comment by blowmage** [comment]
Closing for reasons outlined on #939.

**Pull request closed without merging**
